[FSTORE-1346] Update doc dependencies
logicalclocks/hopsworks-api pull request #197
Opened 2024-04-09 10:27 UTC by vatj

2024-04-15 11:33 UTC, robzor92 requested changes

2024-04-15 11:33 UTC, robzor92 commented on CONTRIBUTING.md
> -    Checkout your dev branch with modified docs:
The section below here does not render correctly.

2024-04-15 11:33 UTC, robzor92 commented on docs/CONTRIBUTING.md
> -    Checkout your dev branch with modified docs:
The section below here does not render correctly.

2024-04-15 11:33 UTC, robzor92 requested changes
The mkdocs-release workflow fails

2024-04-15 11:35 UTC, robzor92 requested changes
Is there no need to override this one also? https://github.com/logicalclocks/feature-store-api/pull/1275/files

2024-04-30 13:50 UTC, vatj commented
Handled in another PR

2024-04-30 13:50 UTC, closed without merging