[FSTORE-1468] Make numpy optional
logicalclocks/hopsworks-api pull request #338
Opened 2024-09-23 07:57 UTC by aversey

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

2024-10-02 15:34 UTC, manu-sj requested changes

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/core/vector_server.py
>  import avro.schema
```
import avro.io
import avro.schema
```
I think these should also be inside the `HAS_AVRO` check

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/core/vector_server.py
> +            if not HAS_AVRO:
I think the entire function `build_complex_feature_decoders` needs the `avro` libary to work since https://github.com/logicalclocks/hopsworks-api/blob/bfbe7aabed58931be068c54fcbc23a72d3294396/python/hsfs/core/vector_server.py#L1075 requires `avro`.

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/python.py
> +    from hsfs.core.type_systems import PYARROW_HOPSWORKS_DTYPE_MAPPING
Missed to remove line https://github.com/logicalclocks/hopsworks-api/blob/bfbe7aabed58931be068c54fcbc23a72d3294396/python/hsfs/engine/python.py#L90

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/python.py
The `profile` function (https://github.com/logicalclocks/hopsworks-api/blob/bfbe7aabed58931be068c54fcbc23a72d3294396/python/hsfs/engine/python.py#L529) also only works if `PYARROW_HOPSWORKS_DTYPE_MAPPING`. So I think that function can also be marked with a decorator as requires `uses_arrow` so that an error is thrown if `PyArrow` is not installed.

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/spark.py
>  import pandas as pd
Missed to do the import with `HAS_PANDAS` check.

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/spark.py
> +            ok = True
Just curious, is there really a need for the `ok` variable can't we just re-raise the exception like you have done for the above case.

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/spark.py
> +                dataframe[:, n_col] = dataframe[:, n_col].map(
Isn't `dataframe` here a numpy array. I don't think numpy array has a map function so I think you would have to resort to list comprehension of something like that. https://stackoverflow.com/questions/74879121/efficiently-localize-an-array-of-datetimes-with-pytz

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/spark.py
> +        # convert timestamps to current timezone
I think the below conversion using `numpy` in the case `pandas` is not installed might not be easy implement. The problems I see is that `numpy` `datetime64` is timezone naive (https://numpy.org/doc/stable/reference/arrays.datetime.html). So it does not store timezone information. So in order to explicilty add information of local timezone they would have to be converted back to python `datetime` objects or a pandas `dataframe`.

2024-10-02 15:34 UTC, manu-sj commented on python/hsfs/engine/spark.py
> +        # We have neither numpy nor pandas, so there is no need to transform timestamps
Here too if `pandas` is not installed we need to perform the same timezone localization done in `convert_numpy_to_spark_dataframe` if the dataframe (list) conatins columns with datetime objects.

2024-10-03 06:58 UTC, aversey commented on python/hsfs/engine/spark.py
>  import pandas as pd
To be done in a separate pandas optionality PR.

2024-10-03 08:35 UTC, aversey commented on python/hsfs/engine/spark.py
> +            ok = True
In contrast to the above, here we need to throw a TypeError if there were no TypeError raised by the code in try. So, I think this is the easiest solution.

2024-10-03 08:37 UTC, aversey commented on python/hsfs/engine/python.py
No, it will work even without pyarrow. If pyarrow is not present, PYARROW_HOPSWORKS_DTYPE_MAPPING is an empty map. I changed all `PYARROW_HOPSWORKS_DTYPE_MAPPING[key]` to `PYARROW_HOPSWORKS_DTYPE_MAPPING.get(key, None)` so that the checks will be false if pyarrow is not installed.

2024-10-04 08:10 UTC, manu-sj approved these changes

2024-10-04 08:15 UTC, merged